
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# Dolibarr V20
#
################################################################################

services:

    ################################################################################
    # Dolibarr V20
    dol-20:
        image:              dolibarr/dolibarr:20
        container_name:     v20.dolibarr.local
        depends_on:
            - mysql
        links:
            - mysql
        working_dir:        /var/www/html/custom
        environment:
            - "DOLI_DB_TYPE=mysqli"
            - "DOLI_DB_HOST=mysql"
            - "DOLI_DB_NAME=dolibarr20"
            - "DOLI_DB_USER=root"
            - "DOLI_DB_PASSWORD=dolibarr"
            - "DOLI_ADMIN_LOGIN=Admin"
            - "PHP_MEMORY_LIMIT=-1"
            - "SPLASH_WS_ID=ThisIsDol20Key"
            - "SPLASH_WS_KEY=ThisTokenIsNotSoSecretChangeIt"
            - "SPLASH_WS_HOST=http://172.100.0.100/ws/soap"
        volumes:
            - "../:/var/www/html/custom/"
            - "../.git/:/var/www/html/custom/.git/"
        entrypoint:         sh /var/www/html/custom/docker/docker-entrypoint.sh
        hostname:           v20.dolibarr.local
        networks:
            default:        { ipv4_address: 172.100.0.20 }
            splashsync:     { aliases: [ v20.dolibarr.local ] }